[[redirects]]
  from = "/sitemap.xml"
  to = "https://qootzfndochmcoijnwxf.supabase.co/functions/v1/sitemap"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"